"""create_tenant_tables

Revision ID: 30a51800a2c6
Revises: bf603f8cebe1
Create Date: 2026-07-13 17:31:26.316033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30a51800a2c6"
down_revision: Union[str, Sequence[str], None] = "bf603f8cebe1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("money", sa.Integer(), nullable=False),
        sa.Column("creation_date", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_actions_creation_date"),
        "audit_actions",
        ["creation_date"],
        unique=False,
    )
    cash_table = op.create_table(
        "cash",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("initial_cash", sa.Integer(), nullable=False),
        sa.Column("current_cash", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    op.bulk_insert(cash_table, [{"id": 1, "initial_cash": 0, "current_cash": 0}])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cash")
    op.drop_index(op.f("ix_audit_actions_creation_date"), table_name="audit_actions")
    op.drop_table("audit_actions")
    # ### end Alembic commands ###
